import styles from "@/styles/Classique.module.css";
import Image from "next/image";
import Head from "next/head";
import Header from "@/components/Header";
import { motion } from "framer-motion";
import { useMotionValue } from "framer-motion";
import { useEffect } from "react";
import { defautTransition } from "@/utils";
import { useRouter } from "next/router";
export default function Soiree() {
    const bgColor = useMotionValue('white')
    const router = useRouter()
    useEffect(() => {


        bgColor.set('black')


    }, [])

    return (
        <>

            <Head>
                <title>Soirée - CAPAUCABANA</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/logo_normal_small.svg" />
            </Head>
            <Header />


            <motion.div className={styles.centerElement}
                style={{ backgroundColor: bgColor, transition: 'background-color 1s ease-in-out' }}
                transition={defautTransition}
                onClick={() => router.push('/images/tck.jpg')}
            >

                <div className={styles.soir}>

                
                    <motion.img src={"/images/sc.png"} 
                        animate={{ scale: 1.02 ,
                            shadow: '0px 0px 20px 0px rgba(0,0,0,0.75)',
                        }}
                        transition={{
                          ...defautTransition,
                          repeat: Infinity,
                          repeatType: "reverse"
                        }}
                    />

                    </div>
                
            </motion.div>
            
        </>
    )
}